#!/usr/bin/env bash
set -euo pipefail

TOPIC="${1:-cash-registers}"
MODEL="${2:-qwen2.5-coder:7b}"

PROMPT_PATH="tools/local-research/prompts/${TOPIC}.md"
PATTERN_PATH="tools/local-research/topics/${TOPIC}.patterns"
OUT_DIR="docs/research/inbox"
OUT_FILE="${OUT_DIR}/${TOPIC}.md"
RAW_DIR="tools/local-research/generated"
SNIPPETS_FILE="${RAW_DIR}/${TOPIC}.snippets.md"

OLLAMA_URL="${OLLAMA_URL:-http://$(ip route | awk '/default/ {print $3}'):11434}"
CONTEXT_LINES="${CONTEXT_LINES:-8}"
MAX_LINES="${MAX_LINES:-900}"
NUM_CTX="${NUM_CTX:-32768}"

ROOTS=(
  "assembly/Assembly-CSharp/Il2CppScheduleOne"
  "assembly/S1API.Il2Cpp.MelonLoader-1"
  "assembly/S1MAPI_Il2Cpp"
  "/home/imetto/projects/mods/OTC-S1-Mod/OverTheCounter"
)

usage() {
  cat <<EOF
Usage:
  tools/local-research/run-research.sh <topic> [model]

Examples:
  tools/local-research/run-research.sh cash-registers
  tools/local-research/run-research.sh grow-tents qwen2.5-coder:7b

Environment:
  OLLAMA_URL     Defaults to Windows host from WSL route.
  CONTEXT_LINES  Lines around each rg match. Default: 8.
  MAX_LINES      Max snippet lines before truncation. Default: 900.
  NUM_CTX        Ollama context window. Default: 32768.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ ! -f "$PROMPT_PATH" ]]; then
  echo "Missing prompt: $PROMPT_PATH" >&2
  exit 1
fi

if [[ ! -f "$PATTERN_PATH" ]]; then
  echo "Missing topic patterns: $PATTERN_PATH" >&2
  exit 1
fi

command -v rg >/dev/null || { echo "Missing dependency: rg" >&2; exit 1; }
command -v jq >/dev/null || { echo "Missing dependency: jq" >&2; exit 1; }
command -v curl >/dev/null || { echo "Missing dependency: curl" >&2; exit 1; }

mkdir -p "$OUT_DIR" "$RAW_DIR"

SEARCH_ROOTS=()
for root in "${ROOTS[@]}"; do
  [[ -d "$root" ]] && SEARCH_ROOTS+=("$root")
done

if [[ "${#SEARCH_ROOTS[@]}" -eq 0 ]]; then
  echo "No search roots exist. Check assembly/ and OTC paths." >&2
  exit 1
fi

{
  echo "# Source snippets for ${TOPIC}"
  echo
  echo "Generated by tools/local-research/run-research.sh"
  echo
  echo "## Search roots"
  for root in "${SEARCH_ROOTS[@]}"; do
    echo "- ${root}"
  done
  echo
  echo "## Topic patterns"
  sed 's/^/- `/' "$PATTERN_PATH" | sed 's/$/`/'
  echo
  echo "## Matches"
  set +o pipefail
  rg --line-number --context "$CONTEXT_LINES" --ignore-case --glob '*.cs' \
    --glob '!**/DebugHelpers.cs' \
    --file "$PATTERN_PATH" "${SEARCH_ROOTS[@]}" \
    | head -n "$MAX_LINES"
  set -o pipefail
} > "$SNIPPETS_FILE"

if ! rg -q '^/.+\.cs-|^/.+\.cs:' "$SNIPPETS_FILE" && ! rg -q '^assembly/.+\.cs-|^assembly/.+\.cs:' "$SNIPPETS_FILE"; then
  echo "No C# snippets matched topic '${TOPIC}'. See $SNIPPETS_FILE" >&2
  exit 1
fi

TMP_PROMPT="$(mktemp)"
trap 'rm -f "$TMP_PROMPT"' EXIT

{
  cat "$PROMPT_PATH"
  echo
  echo "# Instructions for this run"
  echo
  echo "- Use only the snippets below as evidence."
  echo "- Every claim must cite a file path and symbol or line context from the snippets."
  echo "- If evidence is incomplete, say exactly what narrow search should be run next."
  echo "- Do not produce implementation code."
  echo "- Write research notes suitable for review before promotion into docs/research/."
  echo
  cat "$SNIPPETS_FILE"
} > "$TMP_PROMPT"

echo "Topic: $TOPIC"
echo "Model: $MODEL"
echo "Ollama: $OLLAMA_URL"
echo "Snippets: $SNIPPETS_FILE"
echo "Output: $OUT_FILE"

jq -n \
  --arg model "$MODEL" \
  --rawfile prompt "$TMP_PROMPT" \
  --argjson num_ctx "$NUM_CTX" \
  '{
    model: $model,
    prompt: $prompt,
    stream: false,
    options: {
      temperature: 0.1,
      num_ctx: $num_ctx
    }
  }' \
| curl -fsS "$OLLAMA_URL/api/generate" \
    -H "Content-Type: application/json" \
    -d @- \
| jq -r '.response' > "$OUT_FILE"

echo "Done. Review $OUT_FILE, then promote verified facts into docs/research/."
